### ISSUE TITLE
Can you make the text closer to the highlighted view?

### ISSUE THREAD

**Issue by Sweeper777** [bvankuik/DVITutorialView#2]
On an iPad, when the highlighted view is at the top, the text still appears at the bottom. Can you change it so that the text will always be next to the highlighted view, or be on top of it if there is not enough space?

**Comment by bvankuik** [comment]
I currently don't do free support for this project. If you have a budget, then I can make time. Let me know.

**Comment by Sweeper777** [comment]
Okay, I guess I'll close this for now.
